name: Coq

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download Git submodules
        run: git submodule update --init --recursive
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: coqorg/coq:8.17-ocaml-4.14-flambda
          custom_script: |
            startGroup "Install dependencies"
              opam install -y --deps-only CoqOfPython/coq-of-python.opam
              sudo ln -s `which python3` /usr/bin/python
              python --version
            endGroup
            startGroup "Set the rights"
              sudo chown -R $(whoami) .
            endGroup
            startGroup "Translate the Python code to Coq"
              cd ethereum-execution-specs/src
              find ethereum -name "*.py" -print0 | xargs -0 -n 1 python ../../main.py
              cd ../..
            endGroup
            startGroup "Make sure there no differences"
              git diff --exit-code
            endGroup
            startGroup "Compile Coq translations"
              cd CoqOfPython
              make
              cd ..
            endGroup
